### ISSUE TITLE
After clean install avsrun generates PortAudio error

### ISSUE THREAD

**Issue by choughtosh** [xmos/vocalfusion-avs-setup#21]
From clean install using Noobs 2.7.0 the auto_install.sh script completes correctly, but fails when avsrun is called : 

Failed to open PortAudio default stream
Failed to initialize PortAudioMicrophoneWrapper
Failed to create PortAudioMicrophoneWrapper!
Failed to initialize SampleApplication
Failed to create to SampleApplication!

Full DEBUG9 output in file.
[PortAudioError.txt](https://github.com/xmos/vocalfusion-avs-setup/files/1851292/PortAudioError.txt)

**Comment by samchesney** [comment]
Resolved by #22.
