### ISSUE TITLE
Failes to create media player for speech

### ISSUE THREAD

**Issue by oaelectronics** [xmos/vocalfusion-avs-setup#23]
Hi !

I am not able to make an avsrun command on my Pi . See below the messages :

>
xxxxxxxxxxxxxx:~ $ avsrun
2018-05-24 18:41:10.822 [  1] I sdkVersion: 1.4.0

(SampleApp:981): GStreamer-CRITICAL **: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed

(SampleApp:981): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:981): GLib-CRITICAL **: g_source_remove: assertion 'tag > 0' failed
Failed to create media player for speech!
Failed to initialize SampleApplication
Failed to create to SampleApplication!

**Comment by DaveAtkinsonXMOS** [comment]
Hopefully we've moved on from here, so I'm closing this issue. Let us know if the problem re-occurs.
