### ISSUE TITLE
setup.sh continues executing although Building Kernel Modules fails

### ISSUE THREAD

**Issue by ThomasGmeinder** [xmos/vocalfusion-avs-setup#27]
When the loader build step fails as described in issue #28, the setup.sh script carries on executing although this crucial step fails.
Instead it should exit with an error and instruct the user to upgrade to the latest Kernel version with:
sudo apt-get upgrade
sudo reboot

**Comment by larry-xmos** [comment]
Fixed in 09bbe48 and also applied in stereo repository, xmos/vocalfusion-stereo-avs-setup@963a89a

**Comment by larry-xmos** [comment]
Readme now explicitly lists the requirement for kernel headers to match running kernel version. This should avoid failure to build due to version mismatch as per xmos/vocalfusion-rpi-setup#6.
