### ISSUE TITLE
setup.sh fails if Kernel is not up-to-date

### ISSUE THREAD

**Issue by ThomasGmeinder** [xmos/vocalfusion-avs-setup#28]
setup.sh updates the Kernel Header files with:
sudo apt-get install raspberrypi-kernel-headers

This will install the Kernel headers for the latest Kernel version.
If the Kernel is not the latest version then the following module build is likely to fail. 

E.g.:
make -C /lib/modules/4.14.34-v7+/build SUBDIRS=/home/pi/vocalfusion-stereo-avs-setup/vocalfusion-rpi-setup/loader modules
make[1]: *** /lib/modules/4.14.34-v7+/build: No such file or directory. Stop.
Makefile:5: recipe for target 'default' failed

The solution is to upgrade the Kernel:
sudo apt-get upgrade
sudo reboot

Note: The reboot is crucial. Otherwise important links won’t be updated.
E.g. uname -r will still show the old Kernel version although the Kernel was already updated to the latest version

The script or the documentation should ensure that the above upgrade and reboot commands are executed before building the loader

**Comment by larry-xmos** [comment]
Additional instruction step in rpi repository version 1.2.1 should stop this issue from occurring, see xmos/vocalfusion-rpi-setup@ce4b7b4
