### ISSUE TITLE
Sensory repo not found

### ISSUE THREAD

**Issue by rbultman** [xmos/vocalfusion-avs-setup#43]
I'm trying to follow the instructions for install AVS.  When the script attempts to clone the Sensory repo, it fails, because there are no public Sensory repos.  Is there a workaround for this?

**Comment by lucianomartin** [comment]
Sensory has confirmed that their repo to build the KWD won't be made public, therefore we agreed to remove the support for the Sensory KWD in the Vocalfusion AVS setup.

From release https://github.com/xmos/vocalfusion-avs-setup/releases/tag/v3.1.0 all the setups will build, but as there is no KWD on host, the user has to press 't'+ENTER ('tap-to-talk') on the AVS console to go to listening mode.  The only exceptions are XVF3615-INT and XVF3615-UA, these devices have an embedded Alexa KWD which interacts with the AVS console.
