### ISSUE TITLE
At least one link in readme file is not working

### ISSUE THREAD

**Issue by lucianomartin** [xmos/vocalfusion-avs-setup#45]
The following links from the readme file must be updated as it is not working

  - XVF3610: https://www.xmos.ai/file/xvf3610-dev-kit-setup-guides

**Comment by kohtzk** [comment]
This link is also not working:

- XVF3615: https://www.xmos.ai/file/xvf3615-dev-kit-setup-guides

**Comment by kohtzk** [comment]
The following links are also not working:

- XVF3615-INT: https://www.xmos.ai/file/xvf3615-int-release
- XVF3615-UA: https://www.xmos.ai/file/xvf3615-ua-release
- XVF3610-INT: https://www.xmos.ai/file/xvf3610-int-release
- XVF3610-UA: https://www.xmos.ai/file/xvf3610-ua-release

**Comment by kieran-kohtz** [comment]
The 3610 and 3615 dev kit setup guide links should probably be replaced with a link to the 3610 quick start guide.
As far as I know there is no setup guides zip for 3610/15.
https://www.xmos.ai/download/XVF3610-Quick-start-guide(1).pdf

**Comment by tomblackie-xmos** [comment]
Links in readme ae been updated and product names corrected.  For 3615 added note that we require user to contact XMOS for firmware due to additional licencing terms from Amazon.
