### ISSUE TITLE
Installing xvf3615-int setup after xvf3615-ua setup causes the AVS setup to crash

### ISSUE THREAD

**Issue by lucianomartin** [xmos/vocalfusion-avs-setup#47]
This problem occurred only once, so it is not easy to reproduce.

Steps to reproduce issue:
1.  Install xvf3615-ua setup by doing "./auto_install.sh xvf3615-ua" and following the usual instructions
2. Test xvf3615-ua  setup is working
3. Install xvf3615-int setup by doing "./auto_install.sh xvf3615-int" and following the usual instructions
4. Check if avsrun works. With this issue the avsrun was failing  to start due to a problem with portaudio. Audacity was not able to record audio with the xvf3615-int either.

To fix the issue we had to reflash the SD card with Raspian and repeat "./auto_install.sh xvf3615-int"

**Comment by mbanth** [comment]
Fix this problem by adding a recommendation to use a clean RPi setup to the instructions.

**Comment by lucianomartin** [comment]
A recommendation has been added in release https://github.com/xmos/vocalfusion-avs-setup/releases/tag/v3.1.0
