### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by kohtzk** [xmos/vocalfusion-avs-setup#50]
This issue will track small issues related to the readme

**Comment by kohtzk** [comment]
When running `./auto_install.sh xvf3615-ua`
I got the error message `--   No package 'libevdev' found`
This was fixed by installing libevdev-dev using apt install
If packages need to be installed, should this be reflected in the readme?

**Comment by kohtzk** [comment]
Regarding step 9 of AVS SDK installation and Raspberry Pi audio setup

> If you selected the option to run the Sample App on boot you should now be able to complete the registration by following the instructions on the screen, although you may need to scroll back to see them. A code will be printed on the screen, and you will be prompted to visit https://amazon.com/us/code, log in to your developer account, and enter the code when prompted.

I did select the option to start on boot, I couldn't see any instructions or anything indicating that the app is running. I'm also not sure what 'scroll back' means in the context of the raspberry pi desktop.

I think that these parts of step 9 should be clarified.

**Comment by kieran-kohtz** [comment]
In the prerequisites, there is a list of which speaker setups should be used for which board/firmwares

> Powered speakers with audio 3.5mm analogue plug
> - Stereo for the XVF3610, XVF3510 and XVF3500, or Mono for the XVF3100 and XVF3000

This list does not include the 3615, which I know is the same as the 3610, but an external consumer may not

**Comment by kieran-kohtz** [comment]
> Regarding step 9 of AVS SDK installation and Raspberry Pi audio setup
> 
> > If you selected the option to run the Sample App on boot you should now be able to complete the registration by following the instructions on the screen, although you may need to scroll back to see them. A code will be printed on the screen, and you will be prompted to visit https://amazon.com/us/code, log in to your developer account, and enter the code when prompted.
> 
> I did select the option to start on boot, I couldn't see any instructions or anything indicating that the app is running. I'm also not sure what 'scroll back' means in the context of the raspberry pi desktop.
> 
> I think that these parts of step 9 should be clarified.

After more testing it seems like it just didn't start on boot, and 'scroll back' referred to a terminal window, which makes much more sense.

I think the readme should mention that the app should start running in a terminal that the user can see.

**Comment by lucianomartin** [comment]
This has been fixed in release https://github.com/xmos/vocalfusion-avs-setup/releases/tag/v3.1.0
