### ISSUE TITLE
Readme and Quick Start Guide Clash - 3610/15

### ISSUE THREAD

**Issue by kieran-kohtz** [xmos/vocalfusion-avs-setup#51]
The readme says that you can use 3610/15 in both ua and int configs

The quick start guide says that you need to use the int variant. There are also no instructions for setting up the ua variant in the quick start guide

The readme also says that you should use stereo speakers for 3610, but in the quick start guide only shows one speaker

https://www.xmos.ai/download/XVF3610-Quick-start-guide(1).pdf

**Comment by tomblackie-xmos** [comment]
The quick start guide is intended to get new users operational as soon as they open the box.  No set-up is required for the -UA variant as the XK-VOICE-L71 is pre-configured to be a -UA.

The hardware setup instructions have been extended to clarify that a USB cable is required and should be connected between the Pi and the Voice board.

Instructions for setting up a -INT version as an AVS client are shown on page 2 of the quick start guide - they point to this repo for the step-by-step details.

The quick start guide has a picture showing one speaker, but the text underneath indicates that both mono or stereo speakers can be used.  A note was added to the readme that both are valid.

**Comment by tomblackie-xmos** [comment]
closed as requested by @mbanth
