### ISSUE TITLE
Verify VocalFusion AVS Setup

### ISSUE THREAD

**Issue by mbanth** [xmos/vocalfusion-avs-setup#52]
Verify against:

- XVF3615-UA
- XVF3615-INT
- XVF3610-UA
- XVF3610-INT
- XVF3510-INT
- XVF3500
- XVF3100
- XVF3000

**Comment by kieran-kohtz** [comment]
3615-int works

**Comment by kieran-kohtz** [comment]
xvf3510 does not work: https://github.com/xmos/vocalfusion-avs-setup/issues/53

**Comment by kieran-kohtz** [comment]
xvf3500 doesn't work: https://github.com/xmos/vocalfusion-avs-setup/issues/54

**Comment by kieran-kohtz** [comment]
xvf3610-int does not work: https://github.com/xmos/vocalfusion-avs-setup/issues/54
