### ISSUE TITLE
Verify VocalFusion AVS Setup

### ISSUE THREAD

**Issue by mbanth** [xmos/vocalfusion-avs-setup#55]
Verify that setting up VocalFusion AVS using the avs-device-sdk, vocalfusion-avs-setup and vocalfusion-rpi-setup repositories works as documented in their Read Me files.

This work depends on completion of issues #53 and #54.  It follows on from issue #52.

Verify against:

- XVF3615-UA
- XVF3615-INT
- XVF3610-UA
- XVF3610-INT
- XVF3510-INT
- XVF3500
- XVF3100
- XVF3000

**Comment by lucianomartin** [comment]
After a discussion with @mbanth and @tomblackie-xmos, it is agreed thatthe following setups in the given order will be tested:

1. XVF3615-INT (GPIO KWD)
2. XVF3500 (used as I2S master)
3. XVF3615-UA (to test UA setup and HID KWD)
4. XVF3610-INT (push to talk)
5. XVF3510-INT (push to talk) 

For each test the following steps will be peformed:
a. Flash a new SD card and install Raspian
b Configure the RaspberryPi by using ./auto_install.sh xvf3XXX
c. Connect the board and the speakers
d. Test microphones and speakers: use the correct KWD trigger, ask "what time is it?" and listen to the reply

**Comment by lucianomartin** [comment]
All five configurations were tested successfully
