### ISSUE TITLE
Release version 3.1.0 of vocalfusion-avs-setup

### ISSUE THREAD

**Issue by lucianomartin** [xmos/vocalfusion-avs-setup#59]

**Comment by mbanth** [comment]
@lucianomartin, please add links to all PRs involved.  Thanks.

**Comment by lucianomartin** [comment]
The releases comprises of the following PRs so far:
  - https://github.com/xmos/vocalfusion-rpi-setup/pull/42
  - https://github.com/xmos/avs-device-sdk/pull/77

**Comment by lucianomartin** [comment]
The last PR has been merged:
https://github.com/xmos/vocalfusion-avs-setup/pull/60
and the new release has been created:
https://github.com/xmos/vocalfusion-avs-setup/releases/tag/v3.1.0
