### ISSUE TITLE
Integrate Amazon WW and agree on how to distribute necessary files.

### ISSUE THREAD

**Issue by lucianomartin** [xmos/vocalfusion-avs-setup#68]
XMOS has requested the necessary files to Amazon. When the files are ready we could start the work to integrate them for all products except XVF3615.

PM must decide on how to make the Amazon files available to the users.

**Comment by mbanth** [comment]
The User Guide now includes a section instructing the customer how to integrate an Amazon Wake Word model with an XMOS XVF3615 executable.  Consequently, this issue is complete.
