### ISSUE TITLE
Remove obsolete code

### ISSUE THREAD

**Issue by lucianomartin** [xmos/vocalfusion-avs-setup#69]
In avs-device-sdk  and vocalfusion-rpi-setup XMOS introduced code which is not in use anymore.
These are the parts that must be considered:

- [ ] code specific to XVF3510: see use of `PI_HAT_CTRL` in avs-device-sdk and several places in vocalfusion-rpi-setup
- [ ] code specific to XVF3510 sales demo in avs-device-sdk
- [ ] code specific to Sensory engine: see use of `SENSORY_OP_POINT` in avs-device-sdk
- [ ] code specific to XMOS AVS tests which were performed with Sensory engine: see use of `XMOS_AVS_TESTS` in avs-device-sdk

Removing this code will greatly simplify updating the XMOS avs-device-sdk to new version of the SDK from the Alexa repo.

**Comment by mbanth** [comment]
@lucianomartin, please set a Story Point value for this issue.  Thanks.

**Comment by lucianomartin** [comment]
I set 3 Story Points: 1 for implementation and 2 for testing.
