### ISSUE TITLE
Check if latest release of Raspbian, Bullseye, produces the correct I2S clocks

### ISSUE THREAD

**Issue by lucianomartin** [xmos/vocalfusion-avs-setup#70]
We are using the latest version of Buster OS at the moment and the BCLK is not a multiple of the BCLK.
See https://github.com/xmos/sw_xvf3800/issues/134 for more details.

**Comment by mbanth** [comment]
@lucianomartin, please provide a Story Point value for this issue.  Thanks.

**Comment by xhuw** [comment]
During investigations for https://github.com/xmos/sw_xvf3800/issues/134 I tested bullseye (most recent stable release as of when I did that issue) and the BCLK phase issue was present the same as it is in Buster. With that I think this issue can be closed

**Comment by lucianomartin** [comment]
Thanks @xhuw for the confirming. I will close this issue.
