### ISSUE TITLE
Add support for XVF3800

### ISSUE THREAD

**Issue by mbanth** [xmos/vocalfusion-avs-setup#71]
Make the necessary changes so that a customer using a Raspberry Pi coupled with an XVF3800 can use this repository to set up use with AVS correctly and easily.

**Comment by mbanth** [comment]
@lucianomartin, please provide a Story Point value for this issue.  Thanks.

**Comment by lucianomartin** [comment]
No change is required by this issue, but I will make some tests to ensure the XVF3800 works using the 'tap-to-talk' mode.

**Comment by mbanth** [comment]
> I will run the tests when #71 is completed.

Did you mean when #73 is completed?  Issue #71 is this issue.

**Comment by lucianomartin** [comment]
> > I will run the tests when #71 is completed.
> 
> Did you mean when #73 is completed? Issue #71 is this issue.

Correct, I meant #73. As that PR has been closed without being merged, we can keep this issue open and include those changes here.

**Comment by mbanth** [comment]
We have agreed that no more work will take place on this issue.
