### ISSUE TITLE
Update recommended Raspian version 

### ISSUE THREAD

**Issue by lucianomartin** [xmos/vocalfusion-avs-setup#74]
This [section](https://github.com/xmos/vocalfusion-avs-setup/blob/master/README.md#create-a-raspberry-pi-system-disk) must be updated and the new version must be tested.
**Note:** Using Bullseye requires https://github.com/xmos/avs-device-sdk/issues/85

**Comment by lucianomartin** [comment]
I assigned 3 story points as it will take some time to test all the necessary configurations.

**Comment by Allan-xmos** [comment]
The vocalfusion-rpi-setup readme should also be updated https://github.com/xmos/vocalfusion-rpi-setup/blob/master/README.md?plain=1#L53

**Comment by mbanth** [comment]
@lucianomartin, if we include [AVS Device SDK issue 85](https://github.com/xmos/avs-device-sdk/issues/85) and issue #69 in the next release, should we include this issue also?

**Comment by lucianomartin** [comment]
> @lucianomartin, if we include [AVS Device SDK issue 85](https://github.com/xmos/avs-device-sdk/issues/85) and issue #69 in the next release, should we include this issue also?

yes,  [AVS Device SDK issue 85](https://github.com/xmos/avs-device-sdk/issues/85)  and this issue are dependent on each other.

**Comment by mbanth** [comment]
> > @lucianomartin, if we include [AVS Device SDK issue 85](https://github.com/xmos/avs-device-sdk/issues/85) and issue #69 in the next release, should we include this issue also?
> 
> yes, [AVS Device SDK issue 85](https://github.com/xmos/avs-device-sdk/issues/85) and this issue are dependent on each other.

Thanks for confirming.  Since this issue mentions an update to the vocalfusion-rpi-setup's Read Me, does the vocalfusion-rpi-setup require an update for the release, or can we leave the RPi Read Me alone?
